version: '3'
services:
  mariadb:
    image: bitnami/mariadb:10.8
    volumes:
      - ./db:/bitnami/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: strapi
      MARIADB_DATABASE: strapi
      MARIADB_USER: strapi
      MARIADB_PASSWORD: strapi
    user: "${UID:-1000}"

  strapi:
    container_name: strapi
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend/app/src:/opt/app/src
      - ./backend/app/database:/opt/app/database
      - ./backend/app/config:/opt/app/config
      - ./backend/app/public:/opt/app/public
    ports:
      - '1337:1337'
    depends_on:
      - mariadb
