version: '3'
services:
  strapi:
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: "toBeModified1,toBeModified2"
      API_TOKEN_SALT: tobemodified
      ADMIN_JWT_SECRET: tobemodified
      JWT_SECRET: tobemodified
  vue:
    environment:
      VITE_STRAPI_API_KEY: yep-modify-this-one-too
